### ISSUE TITLE
sudo resource question

### ISSUE THREAD

**Issue by pantocrator27** [chef-cookbooks/sudo#101]
### Cookbook version
3.4.0

### Chef-client version
12 & 13

### Platform Details
All 

### Question:
If you are using the sudo resource without using the default recipe of the cookbook, should the resource also care for installing the sudo package if it is not already present?  The reason I ask is that I work in a company where the sudo list is programmatically managed and is outside of the realm of my control.  So I would not have the need to use the default recipe but do have the need for the sudo resource.

**Comment by tarcinil** [comment]
@pantocrator27 

The use of the custom resource will not handle the install of sudo package.

As long of your wrapper cookbook has a dependency on this cookbook, you could manage the package in your wrapper and use the custom resource as you need.  Does your organization's sudoers file include the following `#includedir /etc/sudoers.d`? 

Your sudo version is newer than 1.7.2 if not using the resource will not accomplish anything as sudo will not include those directives.

```
package 'sudo' do
  not_if 'which sudo'
end
```

**Comment by pantocrator27** [comment]
@tarcinil I figured out how to make it work.  The real question is should the custom resource handle the package install also occur in the custom resource?

**Comment by iennae** [comment]
@pantocrator27 It should, and we'll sort that out later this week.

**Comment by iennae** [comment]
release 3.5.0 includes installing the package.

**Comment by pantocrator27** [comment]
I am still receiving the error with the updated cookbook:

```
    ================================================================================
    Error executing action `install` on resource 'sudo[made-up-user]'
    ================================================================================
    
    Errno::ENOENT
    -------------
    No such file or directory - visudo
    
    Cookbook Trace:
    ---------------
    /opt/kitchen/cache/cookbooks/sudo/providers/default.rb:49:in `validate_fragment!'
    /opt/kitchen/cache/cookbooks/sudo/providers/default.rb:104:in `render_sudoer'
    /opt/kitchen/cache/cookbooks/sudo/providers/default.rb:126:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /opt/kitchen/cache/cookbooks/chassis-users/recipes/default.rb
    
     23:     sudo user do
     24:       user user
     25:       nopasswd true
     26:     end
     27: 
    
    Compiled Resource:
    ------------------
    # Declared in /opt/kitchen/cache/cookbooks/chassis-users/recipes/default.rb:23:in `block in from_file'
    
    sudo("made-up-user") do
      action :install
      updated true
      updated_by_last_action true
      default_guard_interpreter :default
      supports {:report=>true, :exception=>true}
      declared_type :sudo
      cookbook_name "chassis-users"
      recipe_name "default"
      user "made-up-user"
      nopasswd true
    end
    
    System Info:
    ------------
    chef_version=13.0.118
    platform=ubuntu
    platform_version=16.04
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
    program_name=chef-client worker: ppid=9;start=02:48:29;
    executable=/opt/chef/embedded/bin/chef-client
```

**Comment by pantocrator27** [comment]
It seems like the issue may be the following:

```
  package 'sudo' do
    not_if 'which sudo'
  end

  unless ::File.exist?(target)
    sudoers_dir = directory target
    sudoers_dir.run_action(:create)
  end
```

It appears as if the sudoers_dir is being run compile time which the package installation is being run converge time ....

**Comment by pantocrator27** [comment]
also, is the `not_if` really necessary?

**Comment by iennae** [comment]
yes, if it's already available because someone has installed it via a non-OS package resource, installing it again would cause issues which is the purpose of the not_if in this case.

**Comment by pantocrator27** [comment]
Fair enough on the guard explanation.  How do we now get the bug about
compile vs converge behavior.

**Comment by iennae** [comment]
Please open a separate issue for tracking that issue. It's helpful to have one problem per issue. This week is ChefConf and Monitorama so this will take some time to get back to. Thanks.

**Comment by pantocrator27** [comment]
No worries.  I am at ChefConf this week as well.   Thanks!

**Comment by pantocrator27** [comment]
ping
