### ISSUE TITLE
sudo resource chokes on group strings

### ISSUE THREAD

**Issue by bby-bishopclark** [chef-cookbooks/sudo#118]
### Cookbook version
3.5.3

### Chef-client version
13.7.16

### Platform Details
enterprise linux 7

### Scenario:
https://github.com/chef-cookbooks/sudo/blob/master/providers/default.rb#L84 doesn't proper prepend group-marker to group list in string.

````
sudo 'app_admins'  do
  group 'web_admins,db_admins'
  commands  ['/sbin/service httpd restart']
end
````

-> /etc/sudoers.d/app_admins
````
%web_admins,db_admins ALL(ALL)=ALL /sbin/service httpd restart
````
### Steps to Reproduce:
as in scenario

### Expected Result:
````
%web_admins,%db_admins ALL(ALL)=ALL /sbin/service httpd restart
````
(with the % prepended on the second group)

### Actual Result:
as in scenario - one leading % only

Hmm.  It doesn't accept `group=>['group1','group2']` right?

**Comment by tas50** [comment]
This is also solved by https://github.com/chef-cookbooks/sudo/commit/0375f154c29f350f0cec981f48e73579be138d81
