### ISSUE TITLE
Chefspec matchers have disappeared between version 4.0.0 and 4.0.1

### ISSUE THREAD

**Issue by hrak** [chef-cookbooks/sudo#123]
### Cookbook version
4.0.1+

### Chef-client version
chef 12.22.1

### Platform Details
Ubuntu 16.04

### Scenario:
my Chefspec tests are failing because the install_sudo and remove_sudo matchers have been removed in version 4.0.1.

### Steps to Reproduce:
any cookbook depending on this cookbook that uses install_sudo chefspec matchers will have failing tests

### Expected Result:
successful chefspec tests :)

### Actual Result:
failing chefspec tests

**Comment by scalp42** [comment]
Unless I'm wrong, I believe ChefSpec `7.1+`  have automatic matchers now, see: https://github.com/chefspec/chefspec#automatic-matchers

Which version are you using? Might be worth upgrading ChefSpec in general 📆

**Comment by hrak** [comment]
Aha, apparently i haven't been keeping up with recent changes :) We're still testing against ChefDK 1.6.x (which has chefspec 6.2.0) in our CI so that probably explains. Thanks!

**Comment by tas50** [comment]
It looks like in the shuffle I missed documenting that the matchers were removed. It's in the changelog now, but for anyone seeing this the solution is to upgrade to a newer release of ChefDK. Not only will you get a much more functional ChefSpec you'll get newer releases of a lot of tools.
