### ISSUE TITLE
Issue with sudoers being created.

### ISSUE THREAD

**Issue by staticfrost** [chef-cookbooks/sudo#129]
### Cookbook version
latest v5.3.3

### Chef-client version
Chef: 13.8.5

### Platform Details
VirtualBox Ubuntu 16.04.4

### Scenario:
I am following https://blog.chef.io/2014/07/10/managing-users-and-ssh-keys-in-a-hybrid-world/ and at the step of adding ;
```
node.default['authorization']['sudo']['passwordless'] = true
 include_recipe "sudo"
```
to default recipe, when I execute chef-client /etc/sudoers.d/ doesn't update with a sysadmin or specific user.

### Steps to Reproduce:
follow:  https://blog.chef.io/2014/07/10/managing-users-and-ssh-keys-in-a-hybrid-world/

### Expected Result:
I should be creating multiple sudoers that have passwordless access

### Actual Result:
No new users or groups are created.

**Comment by tas50** [comment]
Unfortunately that's about 4 years old and not actually the way either of these cookbooks work anymore. This is a resource based cookbook at this point so you have a sudo resource that sets up individual users / groups for sudoers rights. Also the resource to do this is built in Chef 14 so you don't even need this cookbook anymore. Just write a cookbook and user the resource directly.

**Comment by staticfrost** [comment]
Got a link to how its done in Chef 14?

**Comment by tas50** [comment]
There isn't a guide like that for Chef 14, but there are docs for how to use the sudo resource directly. You could create users in a particular group and then setup sudo with the resource for that group. Pretty similar, but done entirely with built in resources so you can skip the whole part about pulling in the cookbooks and what not.  https://docs.chef.io/resource_sudo.html
