### ISSUE TITLE
sudoers.d default setting

### ISSUE THREAD

**Issue by rmoriz** [chef-cookbooks/sudo#51]
Hi,

this issue bytes me every other day: 

When we include_recipe 'sudo' it automatically disables the sudoers.d include (which is enabled by default at least on ubuntu 12.04+14.04). Especially when doing tdd with test-kitchen/vagrant this usually "kills" the vm, because vagrant/test-kitchen users' sudo permissions (which are stored in sudoers.d) get removed (and we have to start over).

Setting default['authorization']['sudo']['include_sudoers_d'] within every cookbook/.kitchen.yml seems to be cumbersome. 

How about changing the defautl['authorization']['sudo']['include_sudoers_d'] to true?

**Comment by nkadel-skyhook** [comment]
Please set it to true!!!

**Comment by kwilczynski** [comment]
I would actually be even more content if the cookbook would do absolutely nothing in `default.rb`. I would love to be able to managed entries under `/etc/sudoers.d` only with the resource, but retain what was initially in the `/etc/sudoers` file. The defaults provided are not necessary something that I would want to have, plus like @rmoriz said, it breaks sudo access for Vagrant / Test Kitchen, etc. What do you think, @cwebberOps?

**Comment by nkadel-skyhook** [comment]
Don't mix the issues, please! I agree that "do not touch /etc/sudoers" is a very reasonable option to have, but leaving /etc/sudoers.d intact is more useful for now.

**Comment by nkadel-skyhook** [comment]
I like the idea, as an option set by role or environment.

Nico Kadel-Garcia
Email: nkadel@gmail.com<mailto:kadel@gmail.com>
Sent from iPhone

On Jul 15, 2015, at 2:33, "Krzysztof Wilczynski" <notifications@github.com<mailto:notifications@github.com>> wrote:


I would actually be even more content if the cookbook would do absolutely nothing in default.rb. I would love to be able to managed entries under /etc/sudoers.d only with the resource, but retain what was initially in the /etc/sudoers file. The defaults provided are not necessary something that I would want to have, plus like @rmoriz<https://github.com/rmoriz> said, it breaks sudo access for Vagrant / Test Kitchen, etc. What do you think, @cwebberOps<https://github.com/cwebberOps>?

**Comment by rmoriz** [comment]
so… can we set this finally to "true"?

**Comment by tas50** [comment]
Let me check the state of distros. With RHEL 5 / Ubuntu 12.04 going away we can probably do it now.

**Comment by tas50** [comment]
This is on my whiteboard to investigate and fix

**Comment by tas50** [comment]
This will be resolved by https://github.com/chef-cookbooks/sudo/pull/110 now that RHEL 5 is EOL.
