### ISSUE TITLE
 /etc/suders file modes on centos 7

### ISSUE THREAD

**Issue by spheromak** [chef-cookbooks/sudo#56]
the setting of 0440 on /etc/sudoers prevents users from using sudo on centos7 

```
kitchen@eef1cd73932e.      ~
$ sudo su -
sudo: unable to open /etc/sudoers: Permission denied
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
```

**Comment by nkadel-skyhook** [comment]
Mode 0440 on /etc/sudoers is correct for CentOS 7. You're apparently encountering another issue.

Do an "ls -ld /etc/sudoers" to get a better handle on the problem.
