### ISSUE TITLE
No way to clear old and erroneous /etc/suders.d entries

### ISSUE THREAD

**Issue by nkadel-skyhook** [chef-cookbooks/sudo#62]
There's no current way for a chef deployment to clear *erroneous* and out of date /etc/suders.d entries. Since sudo entries are order sensitive, non-chef entries parsed early can affect behavior of later entries added by chef, it can actually break chef based sudo deployments if /etc/suders is enabled.

I suggest adding a "clear_sudoers_d" recipe specifically for such cleanup operations, and will be happy to add a patch.

**Comment by bcg62** [comment]
@nkadel-skyhook the zap cookbook tries to address this issue at a higher level. You can probably use it to address this issue. https://github.com/nvwls/zap

**Comment by nkadel-skyhook** [comment]
Thanks for the pointer: there are similar issues for the nagios, bind, and nginx cookbooks.

Nico Kadel-Garcia
Email: nkadel@gmail.com<mailto:kadel@gmail.com>
Sent from iPhone

On Dec 4, 2015, at 11:51, "Brendan Germain" <notifications@github.com<mailto:notifications@github.com>> wrote:


@nkadel-skyhook<https://github.com/nkadel-skyhook> the zap cookbook tries to address this issue at a higher level. You can probably use it to address this issue. https://github.com/nvwls/zap

**Comment by tas50** [comment]
At the moment you have to use the delete action to cleanup old entries.  We don't have a native accumulator concept in chef to properly cleanup non-chef managed data, but we could write something or use zap.  It's probably worth doing.

**Comment by tas50** [comment]
I'm closing this since this is more of a chef-client issue and less of an issue with this cookbook.  We actively manage files and we don't deal with files we don't manage. That's a pretty core concept in Chef and deleting non-managed files in this directory would go against that concept. Nothing stops you from writing logic to look at the sudo resource that have executes and nuke anything else. That's up to you if you feel comfortable executing something like that in your environment.

**Comment by nkadel-skyhook** [comment]
May I respectfully disagree with this approach? 

If it was the "users" or "yum" recipe, I'd agree with your reasoning.  Even "hostsfile" depends on not clearing away various OS published components. 

But tandard package deployment tools do not seem to touch /etc/sudoers.d. And as soon as sudoers.d is activated by the sudo cookbook, then it becomes like /etc/nginx/sites-enabld, which is kept pruned by the "nginx" cookbook", or /etc/httpd/sites-enabled on RHEL, which is kept pruned by the apache2 cookbook. Non-chef-managed entries are automatically cleared, successfully. this allows mere disabling of a chef managed recipe to clear the old configuration file, without having to write local wrappers to *delete* them and force the ongoing use of obsolete recipes in a "remove" mode.

But the persistent use of cookbooks which merely deploy add-on features and never clean up after themselves, and force the  local admin having to write and maintain their local set of wrapper cookbooks to do cleanup as well as deployment, has been problematic. And extra entries in /etc/sudoers.d can *break* chef deployed configurations. So it seems worth some effort.

If I can find cycles to write in a "zap" cleanup, would you be amenable to a pull requiest to support this? Ideally as a "default enabled" option?
