### ISSUE TITLE
sudoe LWRP should warn/error if include_sudoers_d is set to false

### ISSUE THREAD

**Issue by ranjib** [chef-cookbooks/sudo#70]
If include_sudoers_d is set to false (which is default) , sudo LWRP will have no effect. This is documented, but given both attribute and lwrp is offered by the same cookbook, it will be nice to get warning message sudo lwrp is being used, but include_sudoers_d is set to false.

**Comment by jtimberman** [comment]
I like this idea.

**Comment by tas50** [comment]
We should fix this
