### ISSUE TITLE
Only manage sudoer.d

### ISSUE THREAD

**Issue by mpechner** [chef-cookbooks/sudo#76]
Is there a way to make the cookbook not touch /etc/sudoers?
I only want to use it to manage sudoers.d?
If not, I am willing to contribute code.
Have the template use to an attribute?  authorization/sudo/dont_touch_etcsudoers=true
?

What is your preference? 

Or am I the only person who has asked this?

**Comment by mburns** [comment]
If you only use the `sudo` LWRP and don't include `sudo::default` in your run_list, it won't run the logic to managed `/etc/sudoers`.

That being said, there is logic there you might want to have (create the `sudoers.d/` dir and install the `sudo` package.

**Comment by tas50** [comment]
I'm in agreement with @mburns.  You can just use the LWRP if you only want to create .d files.
