### ISSUE TITLE
Cookbook does not have support for User_Alias functionality of sudoers file

### ISSUE THREAD

**Issue by michaelschlies** [chef-cookbooks/sudo#89]
### Cookbook version

master HEAD
### Chef-client version

N/A
### Platform Details

N/A
### Scenario:

Use of User_Alias from the cookbook
### Steps to Reproduce:

There is no support for the User_Alias functionality in the template
### Expected Result:

Like Cmnd_Alias User_Alias should take in a hash of node attributes and supply User_Alias sections to a sudoers file.
### Actual Result:

Not possible as the template does not have support for this functionality.
## 

Edit:
Also I should indicate I'm working on the PR for this right now.

**Comment by nickkeyzer** [comment]
:+1: 

This is something I've just run into that would be very helpful to have. Thank you for your efforts.

**Comment by michaelschlies** [comment]
@nickkeyzer I owe this actually the actual PR. I built the changes for a generic Alias so it can support all Alias types instead of just User_Alias. I am stuck in windows all of today so I can't open it up until later but will make sure I follow up

**Comment by tas50** [comment]
Now that we've moved the resource over to the chef-client itself this change will need to go there. I'm going to close the issue out here.
