### ISSUE TITLE
Confusing warning when using `sudo` resource without including `sudo::default` recipe

### ISSUE THREAD

**Issue by acoulton** [chef-cookbooks/sudo#92]
### Cookbook version
3.1.0

### Chef-client version
12.13.37

### Platform Details
Ubuntu 14.04

### Scenario:
I've for some time been using the `sudo` resource to configure additional users, **without** running the sudo::default recipe to manage the actual /etc/sudoers file (this is just using ubuntu defaults).

On upgrading past version 2.10 today I noticed a worrying warning appearing in my provisioning logs : `WARN: andrew will be rendered, but will not take effect because node['authorization']['sudo']['include_sudoers_d'] is set to false!`. This warning was introduced in #82 

However, it seemed like everything was working as usual post-provisioning. After some digging, I realised that as I'm not using `sudo::default`, my `/etc/sudoers` file isn't being overwritten, and by default ubuntu includes the sudoers.d - so actually the warning is incorrect, my `sudo` resource should (and does) take effect.

### Steps to Reproduce:
Provision on ubuntu with a basic recipe that just defines a `sudo` resource but never runs `sudo::default`.

### Expected Result:
Everything works as before, no warnings.

### Actual Result:
Everything works, but the log output gives a spurious warning that my sudo permissions are about to disappear.

**Comment by tas50** [comment]
@acoulton I'm open to a PR to improve the warning message here, but some versions of sudo need this attribute to be set or the LWRP does nothing. It was put in place to avoid some serious confusion that users were having.

**Comment by tas50** [comment]
This will be fixed by https://github.com/chef-cookbooks/sudo/pull/110

**Comment by acoulton** [comment]
@tas50 that's great, thanks - sorry for never getting back to you on this.
