### ISSUE TITLE
node['authorization']['sudo']['include_sudoers_d'] to true

### ISSUE THREAD

**Issue by pantocrator27** [chef-cookbooks/sudo#95]
I am not sure what setting `node['authorization']['sudo']['include_sudoers_d']` to `true` actually does.  With using the LWRP, I am receiving the warning however that the user is rendered but the rule will not work because `node['authorization']['sudo']['include_sudoers_d']` is set to `false` but the rule still works.  

Can someone provide clarification on what this actually does?  

Thanks!

**Comment by tas50** [comment]
You need to enable pulling in the .d files in the main config. Setting this to true enables that and pulls in files. It's possible that newer versions of sudo always pull in .d files, which really should have been the case from day one. In the past you definitely needed to turn this on to make things work.
