### ISSUE TITLE
Remove 'sysadmin' group default

### ISSUE THREAD

**Issue by cringdahl** [chef-cookbooks/sudo#97]
Please set `default['authorization']['sudo']['groups'] = []` instead of `= ['sysadmin']`. The 'users' cookbook has, of course, deprecated the default 'sysadmin' recipe and group, and this cookbook should follow suit.

Thanks!

**Comment by tas50** [comment]
I did this in the 2.4.0 release based on this issue. Thanks for noticing we left this behind

**Comment by barrowkwan** [comment]
as of version 3.5.0, default['authorization']['sudo']['groups']  still set to sysadmin by default, can this change to [] instead?
